### PR TITLE
#217 rectangular select and copy

### PR DESCRIPTION
**Pull request by rrrooommmaaa**
## Description

Pressing 'Alt' would make the selection region rectangular

Fixes # 217

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Start selection with mouse.
Press left 'Alt'.
The selection region becomes rectangular

**Test Configuration**:
* OS: Windows
* OS version: 1809
* Go version: 1.10.4

### CODE REVIEW

**Comment by cjw296** [comment]
This is almost there, but not quite:

What I'd expect to happen:
- hold down left alt
- drag rectangle to select
- release of mouse button and alt key in any order
- rectangle stays selected

What actually happens:
- hold down left alt
- drag rectangle to select
- releasing the alt key flips the selection back to being line based
- re-pressing the alt key flips it back to being rectangular

**Comment by rrrooommmaaa** [comment]
@cjw296 Yes, this was intentional. I thought it would be convenient if you can change your mind without having to re-select. I haven't seen Mac implementation but I guessed they were smart enough to do this. Well, I suggest to have voting on which is better, among those who care.

**Comment by cjw296** [comment]
Every other rectangular select tool I've used across, Mac, Windows, PyCharm, etc all work as I've described. It would be great if you could switch it to be like that, having to keep Alt held down for the selection to stay rectangular is weird...

**Comment by rrrooommmaaa** [comment]
@cjw296 done

**Comment by cjw296** [comment]
Perfect, thanks!

**Pull request merged**
