### PR TITLE
Avoid polling in main GUI loop

### PR DESCRIPTION
**Pull request by mjs**
## Description

Instead of waking up regularly using WaitEventsTimeout, WaitEvents and PostEmptyEvent are used to make the main loop event driven. The maximum rate of redraws due to terminal activity can be tweaked via the new wakePeriod const.

This leads to some significant performance improvements: Aminal now consumes:
- no CPU when idle (previously ~2.7% on my laptop)
- ~8.5% CPU on my laptop when running htop full screen on a large monitor (previously ~18.5%)
- scrolling large amounts of output is an order of magnitude faster

This change also incidentally fixes data races around the terminal dirty flag (which is now gone).

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

This has seen extensive manual testing on Windows and Linux using cmd.exe, Windows SSH to Linux host, zsh and bash on Linux.

**Test Configuration**:

* OS: Linux and Windows
* OS version: Ubuntu 18.04 and Windows 1809
* Go version: 1.12

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by rrrooommmaaa** [comment]
@mjs Why didn't you put `ditry` notifier to TerminalState? Terminal and buffer share this object already. No need for extra argument in constructor.
@MaxRis I suggest we optimize this

**Comment by MaxRis** [comment]
@rrrooommmaaa will it be fine to add improvements as new separate PR?

**Comment by mjs** [comment]
@rrrooommmaaa I considered putting `dirty` onto TerminalState but given that the dirty state was set for several conditions that don't involve a change to TerminalState it didn't seem like the right place for it.

I'm happy to revisit this later if you think it's worthwhile.

**Comment by rrrooommmaaa** [comment]
@mjs What conditions? Can you give examples, please?

**Pull request merged**
