### PR TITLE
Gofmt

### PR DESCRIPTION
**Pull request by mjs**
## Description

Fix errors reported by gofmt and add checks to prevent future
regressions.

- `make check-gofmt` will check for files that aren't gofmt
- compliant. This will be run by TravisCI.
- `make gofmt` will fix any gofmt errors in Aminal's source
- All existing gofmt have been fixed.

Vendored files are ignored.

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Tested that Aminal still builds and runs.

**Test Configuration**:

* OS: Ubuntu
* OS version: 18.04
* Go version: 1.11.5

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by MaxRis** [comment]
That, probably, should be rebased and merged with priority since it will introduce conflicts to others PRs or others merged PRs will block that PR again and again

**Comment by mjs** [comment]
@liamg @MaxRis rebased

**Comment by MaxRis** [comment]
@mjs oh, it seems that Travis won't pass for your PR. That might be because you're doing it from your fork, but should do from the remote branch of the same repo. I have the same issue in another PR. will update mine and let you know if it helps.

**Comment by MaxRis** [comment]
@mjs you need just to push exactly the same branch from your fork into liamg/aminal repo directly. After you will do push the travis build will magically start for that your PR. No additional actions.

**Pull request merged**
