### PR TITLE
Implementation of the vertical scrollbar

### LINKED ISSUE #89: Scrollbar
When an application produces a lot of output, it is helpful to be able to quickly scroll back. In many cases, even page up/page down are too slow. An optional scrollbar is one way to solve this problem.

### PR DESCRIPTION
**Pull request by nikitar020**
## Description

This PR adds a vertical scrollbar to the Aminal window. Also, there is a new configuration parameter, `show_vertical_scrollbar`, which is `true` by default. The scrollbar supports common functions:

- clicking on top and bottom arrows scrolls one line up or down, correspondingly
- clicking on space between the thumb and top or bottom arrows scrolls one page up or down, correspondingly
- dragging the thumb with the left mouse button scrolls the screen

## Notes

- On hi-res displays it should scale accordingly (but needs to test because I don't have one).
- Also this PR changes Travis settings so that now `gofmt` checks are performed for `Go1.11.x` (most recent version) builds.

Fixes #89 and #154 

## Type of change

- [X] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by liamg** [comment]
This doesn't seem to work for me, though perhaps it's an i3 related issue. The scroll block is near the top of the bar even when I'm at the bottom of the output. It'd be cool to make this a little more aesthetically pleasing too, though I don't have the artistic skill to give any pointers. Hmm, maybe we can talk this over in slack.

**Comment by nikitar020** [comment]
> This doesn't seem to work for me, though perhaps it's an i3 related issue. The scroll block is near the top of the bar even when I'm at the bottom of the output.

@liamg Could you make some screenshots and/or video of the problem, as I'm not able to reproduce it?

**Comment by MaxRis** [comment]
@nikitar020 crash on MacOS seems happens from inside `func (rr *rectangleRenderer) render(left float32, top float32, width float32, height float32, colour config.Colour)`

**Comment by mjs** [comment]
Data points from me: I've run in this on 3K and 4K displays on Linux and Windows and the scrollbar works and scales well. The scroll bar is a little wider than what I'm used to with gnome-terminal and urxvt but it's fine. 

Screenshot on Linux:
image

**Comment by mjs** [comment]
I've just noticed some strange behaviour when the window is resized. See this video:

https://www.dropbox.com/s/6w0ngeamo9cj9k4/scrollbar-resize.mp4?dl=0

The resize is quite slow and the scrollbar lags behind the edge of the window.

This was on Linux and the problem doesn't seem to happen on Windows. I don't think it's a showstopper - this could be fixed in a later PR if you like.

**Comment by nikitar020** [comment]
> I've just noticed some strange behaviour when the window is resized. See this video:
> https://www.dropbox.com/s/6w0ngeamo9cj9k4/scrollbar-resize.mp4?dl=0

@mjs Strange that I've tested this on Linux and there is no such a behavior... I'm suspecting that it might depend on the OpenGL implementation... For testing, I'm using Debian Stretch (in a VM) with Mesa 13.0.6 OpenGL drivers. Which Linux flavor and which drivers are used on our Linux box?

**Comment by nikitar020** [comment]
@MaxRis 
> crash on MacOS seems happens from inside func (rr *rectangleRenderer) render(left float32, top float32, width float32, height float32, colour config.Colour)

Since I cannot test Aminal on MacOS could you please provide a stack trace on that error?

**Comment by MaxRis** [comment]
@nikitar020 have sent in Slack, thanks

**Comment by mjs** [comment]
I can confirm that this work fine on darwin. LGTM.

**Comment by mjs** [comment]
One more thing -  I just tried this out on OSX with a 4K screen and the scaling of the scrollbar is a little off. It's much smaller on the 4K screen than on the 1920x800 screen on this old Mac laptop.

On laptop display:
Screen Shot 2019-03-19 at 12 07 36

On 4K external display:
Screen Shot 2019-03-19 at 12 06 57

This probably isn't serious enough to stop this PR from landing but should be fixed at some point.

**Pull request merged**
