### PR TITLE
Fix merge issues in develop

### PR DESCRIPTION
**Pull request by mjs**
Develop isn't compiling due to recently introduced issues.

### CODE REVIEW

**Comment by MaxRis** [comment]
@mjs  `go test ./...` hangs on Linux (locally as well). Not sure what it might be

**Comment by MaxRis** [comment]
after long delay `go test ./...` finally passed locally, but still waiting for
`xvfb-run --server-args="-screen 0 1024x768x24" make test`

**Comment by MaxRis** [comment]
that should be related to unit tests updates in recent PR.

**Comment by mjs** [comment]
As per Slack, `go test ./...` and `xvfb-run --server-args="-screen 0 1024x768x24" make test` are working fine on my machine. Hopefully the addition of `-timeout` tells us something useful.

**Pull request merged**
